name: Bug Report
description: Thanks for taking the time to fill out this bug report!

body:
  - type: dropdown
    id: affected-iso-version
    attributes:
      label: ISO Version
      description: Which ISO is affected? Mark all if applicable.
      options:
        - DIN70121
        - ISO15118-2
        - ISO15118-20
      multiple: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If applicable, add screenshots or logfiles to help explain your problem.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: |
        If applicable describe the steps and additional information to reproduce the behavior like message communication between EV and EVSE (EXI Stream + XML), compile options and your system information.

  - type: textarea
    id: other
    attributes:
      label: Anything else?
      placeholder: Add any other context about the bug report here.
